#ifndef QSTANDARD_H
#define QSTANDARD_H

#include <QPainter>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QPushButton>
#include <QEvent>
#include <QMouseEvent>
#include <QListView>
#include <QListWidget>
#include <QDebug>
#include <QMenu>
#include <QFileDialog>
#include <QDialog>
#include <QLabel>
#include <QLineEdit>
#include <QComboBox>
#include <QSignalMapper>
#include <QRadioButton>
#include <QApplication>
#include <QMessageBox>
#include <QCheckBox>
#include <QTextEdit>
#include <QRect>
#include <QAbstractScrollArea>
#include <QScrollBar>
#include <QProgressBar>
#include <QMenuBar>
#include <QButtonGroup>
#include <QMainWindow>
#include <QTreeWidget>
#include <QTableWidget>
#include <QHeaderView>
#include <QColor>
#include <QSpinBox>
#include <QSlider>
#include <QGroupBox>
#include <QWidget>
#include <QTreeWidgetItem>
#include <QSettings>
#include <QMdiArea>
#include <QSplitter>
#include <QPointF>
#include <QVector3D>
#include <QPlainTextEdit>

#endif // QSTANDARD_H
